;;;; sicp-explicit-control.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         extras
         sicp-eval
         sicp-machine
         sicp-machine-monitor
         sicp-compile))
(##sys#register-compiled-module
  'sicp-explicit-control
  (list)
  '((compile-and-run-non-repl-test0
      .
      sicp-explicit-control#compile-and-run-non-repl-test0)
    (compile-and-run-non-repl-test
      .
      sicp-explicit-control#compile-and-run-non-repl-test)
    (get-push-depth-statistics
      .
      sicp-explicit-control#get-push-depth-statistics)
    (compile-and-go-test . sicp-explicit-control#compile-and-go-test)
    (eceval-test-2 . sicp-explicit-control#eceval-test-2)
    (eceval-test . sicp-explicit-control#eceval-test)
    (with-primitive-operations
      .
      sicp-explicit-control#with-primitive-operations)
    (with-primitive-procedures-non-tail
      .
      sicp-explicit-control#with-primitive-procedures-non-tail)
    (with-primitive-procedures . sicp-eval#with-primitive-procedures)
    (eceval* . sicp-explicit-control#eceval*)
    (eceval-single-exp . sicp-explicit-control#eceval-single-exp)
    (make-eceval-single-exp . sicp-explicit-control#make-eceval-single-exp)
    (eceval-non-repl . sicp-explicit-control#eceval-non-repl)
    (eceval-non-repl-non-tail . sicp-explicit-control#eceval-non-repl-non-tail)
    (eceval-non-repl-tail . sicp-explicit-control#eceval-non-repl-tail)
    (make-eceval-non-repl . sicp-explicit-control#make-eceval-non-repl)
    (compile-and-go . sicp-explicit-control#compile-and-go)
    (start-eceval . sicp-explicit-control#start-eceval)
    (eceval-repl . sicp-explicit-control#eceval-repl)
    (make-eceval-repl . sicp-explicit-control#make-eceval-repl)
    (eceval-common-non-tail . sicp-explicit-control#eceval-common-non-tail)
    (eceval-common . sicp-explicit-control#eceval-common)
    (ec-unknown-procedure-type
      .
      sicp-explicit-control#ec-unknown-procedure-type)
    (ec-unknown-expression-type
      .
      sicp-explicit-control#ec-unknown-expression-type)
    (ec-ev-definition-1 . sicp-explicit-control#ec-ev-definition-1)
    (ec-ev-definition . sicp-explicit-control#ec-ev-definition)
    (ec-ev-assignment-1 . sicp-explicit-control#ec-ev-assignment-1)
    (ec-ev-assignment . sicp-explicit-control#ec-ev-assignment)
    (ec-ev-if-decide . sicp-explicit-control#ec-ev-if-decide)
    (ec-ev-if . sicp-explicit-control#ec-ev-if)
    (ec-ev-sequence-non-tail . sicp-explicit-control#ec-ev-sequence-non-tail)
    (ec-ev-sequence . sicp-explicit-control#ec-ev-sequence)
    (ec-ev-begin . sicp-explicit-control#ec-ev-begin)
    (ec-compound-apply . sicp-explicit-control#ec-compound-apply)
    (ec-primitive-apply . sicp-explicit-control#ec-primitive-apply)
    (ec-apply-dispatch . sicp-explicit-control#ec-apply-dispatch)
    (ec-ev-appl-accum-last-arg
      .
      sicp-explicit-control#ec-ev-appl-accum-last-arg)
    (ec-ev-appl-last-arg . sicp-explicit-control#ec-ev-appl-last-arg)
    (ec-ev-appl-accumulate-arg
      .
      sicp-explicit-control#ec-ev-appl-accumulate-arg)
    (ec-ev-appl-did-operator . sicp-explicit-control#ec-ev-appl-did-operator)
    (ec-ev-application . sicp-explicit-control#ec-ev-application)
    (ec-ev-compile-and-run . sicp-explicit-control#ec-ev-compile-and-run)
    (ec-ev-lambda . sicp-explicit-control#ec-ev-lambda)
    (ec-ev-quoted . sicp-explicit-control#ec-ev-quoted)
    (ec-ev-variable . sicp-explicit-control#ec-ev-variable)
    (ec-ev-self-eval . sicp-explicit-control#ec-ev-self-eval)
    (ec-eval-dispatch . sicp-explicit-control#ec-eval-dispatch)
    (eceval-operations . sicp-explicit-control#eceval-operations)
    (prim-compile-and-run . sicp-explicit-control#prim-compile-and-run)
    (eceval-machine . sicp-explicit-control#eceval-machine)
    (compile-and-run-exp . sicp-explicit-control#compile-and-run-exp)
    (compile-and-run? . sicp-explicit-control#compile-and-run?)
    (user-print-env . sicp-explicit-control#user-print-env)
    (user-print . sicp-eval#user-print)
    (get-global-environment . sicp-explicit-control#get-global-environment)
    (no-more-exps? . sicp-explicit-control#no-more-exps?)
    (last-operand? . sicp-explicit-control#last-operand?)
    (adjoin-arg . sicp-explicit-control#adjoin-arg)
    (empty-arglist . sicp-explicit-control#empty-arglist))
  (list)
  (list))

;; END OF FILE
